FROM google/dart

# install nodejs
RUN apt-get update -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

# install vulcanize
RUN npm i -g vulcanize

# install the dependence
COPY dart-pad /dart-pad
WORKDIR /dart-pad
ENV PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub"
RUN pub get

# serve as 0.0.0.0 instead of localhost
RUN sed -i 's/localhost/0.0.0.0/g' bin/serve.dart
RUN sed -i 's/localhost:8000/0.0.0.0:8000/g' tool/grind.dart

# install grinder globally
RUN pub global activate grinder

ENTRYPOINT grind serve-custom-backend
