FROM google/dart

# install nodejs
RUN apt-get update -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

# install vulcanize
RUN npm i -g vulcanize

# install the dependence
COPY dart-pad /dart-pad
WORKDIR /dart-pad
RUN pub get

# install grinder globally
RUN pub global activate grinder

